# Generated by Django 3.2.7 on 2021-09-27 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc_Disp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeG_Mil', models.CharField(max_length=20)),
                ('Nome_Mil', models.CharField(max_length=100)),
                ('DtNsc_Mil', models.DateField()),
                ('DtPrac_Mil', models.DateField()),
                ('DtProm_Mil', models.DateField()),
                ('Vsb_Mil', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PostGrad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomde_PG', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_SU', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_TipEsc', models.CharField(max_length=50)),
                ('Id_Mil', models.ManyToManyField(to='PJI110.Militar')),
            ],
        ),
        migrations.CreateModel(
            name='SubTipoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_SubTipEsc', models.CharField(max_length=50)),
                ('Id_TipEsc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PJI110.tipoescala')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PJI110.matriz')),
                ('Id_Mil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PJI110.militar')),
            ],
        ),
        migrations.CreateModel(
            name='Militar_Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Mil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PJI110.militar')),
                ('Id_TipEsc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PJI110.tipoescala')),
            ],
        ),
        migrations.CreateModel(
            name='Militar_Dispensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Disp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PJI110.dispensa')),
                ('Id_Mil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PJI110.militar')),
            ],
        ),
        migrations.AddField(
            model_name='militar',
            name='Id_PG',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PJI110.postgrad'),
        ),
        migrations.AddField(
            model_name='militar',
            name='Id_SU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PJI110.su'),
        ),
        migrations.AddField(
            model_name='matriz',
            name='Id_SubTipEsc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PJI110.subtipoescala'),
        ),
        migrations.AddField(
            model_name='matriz',
            name='Servicos',
            field=models.ManyToManyField(to='PJI110.Militar'),
        ),
        migrations.AddField(
            model_name='dispensa',
            name='Militares',
            field=models.ManyToManyField(to='PJI110.Militar'),
        ),
    ]
