# Generated by Django 3.2.7 on 2021-09-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PJI110', '0002_remove_tipoescala_id_mil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensa',
            name='Militares',
        ),
        migrations.RemoveField(
            model_name='matriz',
            name='Servicos',
        ),
    ]
