# Generated by Django 3.2.7 on 2021-09-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PJI110', '0003_auto_20210927_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postgrad',
            old_name='Nomde_PG',
            new_name='Nome_PG',
        ),
    ]
