# Generated by Django 3.2.7 on 2021-10-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PJI110', '0004_rename_nomde_pg_postgrad_nome_pg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar',
            name='Vsb_Mil',
            field=models.BooleanField(null=True),
        ),
    ]
