# Generated by Django 3.2.7 on 2021-10-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PJI110', '0006_auto_20211016_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar_dispensa',
            name='Begin_Mil_Disp',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='militar_dispensa',
            name='End_Mil_Disp',
            field=models.DateField(blank=True),
        ),
    ]
