# Generated by Django 3.2.7 on 2021-10-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PJI110', '0007_auto_20211016_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militar_dispensa',
            name='Begin_Mil_Disp',
        ),
        migrations.RemoveField(
            model_name='militar_dispensa',
            name='End_Mil_Disp',
        ),
    ]
