# Generated by Django 3.2.7 on 2021-10-16 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PJI110', '0008_auto_20211016_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar_dispensa',
            name='Begin_Mil_Disp',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='militar_dispensa',
            name='End_Mil_Disp',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
