# Generated by Django 3.2.7 on 2021-10-16 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PJI110', '0009_auto_20211016_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar_dispensa',
            name='Begin_Mil_Disp',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 16, 18, 42, 14, 813791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='militar_dispensa',
            name='End_Mil_Disp',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 16, 18, 42, 14, 813791, tzinfo=utc)),
        ),
    ]
