# Generated by Django 3.2.7 on 2021-10-21 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PJI110', '0010_auto_20211016_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtipoescala',
            name='Prioridade_SubTipEsc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='militar_dispensa',
            name='Begin_Mil_Disp',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='militar_dispensa',
            name='End_Mil_Disp',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
