# Generated by Django 3.2.7 on 2021-10-25 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PJI110', '0013_auto_20211024_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoescala',
            name='Militares_TipoEscala',
            field=models.ManyToManyField(through='PJI110.Militar_Tipo', to='PJI110.Militar'),
        ),
        migrations.RemoveField(
            model_name='militar_tipo',
            name='Id_Mil',
        ),
        migrations.AddField(
            model_name='militar_tipo',
            name='Id_Mil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PJI110.militar'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='militar_tipo',
            name='Id_TipEsc',
        ),
        migrations.AddField(
            model_name='militar_tipo',
            name='Id_TipEsc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PJI110.tipoescala'),
            preserve_default=False,
        ),
    ]
