# Generated by Django 3.2.7 on 2021-10-27 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PJI110', '0014_auto_20211025_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar_tipo',
            name='DtSv_P_Mil_TipEsc',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='militar_tipo',
            name='DtSv_V_Mil_TipEsc',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='militar_tipo',
            name='NumSv_P_Mil_TipEsc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='militar_tipo',
            name='NumSv_V_Mil_TipEsc',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
