# Generated by Django 3.2.7 on 2021-10-27 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PJI110', '0015_auto_20211026_2234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='militar_tipo',
            unique_together={('Id_Mil', 'Id_TipEsc')},
        ),
    ]
