# Generated by Django 3.2.7 on 2021-10-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PJI110', '0016_alter_militar_tipo_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='militar',
            options={'ordering': ('-Id_PG', 'DtProm_Mil', 'DtPrac_Mil', 'DtNsc_Mil')},
        ),
        migrations.AlterModelOptions(
            name='subtipoescala',
            options={'ordering': ('Id_TipEsc', 'Prioridade_SubTipEsc')},
        ),
    ]
