# Generated by Django 3.2.7 on 2021-10-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PJI110', '0018_auto_20211031_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matriz',
            options={'ordering': ('Dt_Matriz',)},
        ),
        migrations.AlterField(
            model_name='matriz',
            name='IsHolyday_Matriz',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
