# Generated by Django 3.2.7 on 2021-11-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PJI110', '0019_auto_20211031_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matriz',
            options={'ordering': ('Dt_Matriz', 'Id_SubTipEsc__Id_TipEsc', 'Id_SubTipEsc__Prioridade_SubTipEsc')},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ('Id_Matriz__Dt_Matriz', 'Id_Matriz__Id_SubTipEsc__Id_TipEsc', 'Id_Matriz__Id_SubTipEsc')},
        ),
    ]
